query CurrentUser(
  $allergy: Float
  $ingredients: [Float!]
  $rating: Float
  $nutrition: Float
  $time: Float
) {
  currentUser {
    id
    names
    lastNames
    email
    recipes {
      id
      title
      description
      ingredients
      process
      timeCategory
      nutritionCategory
      portions
      authorId
      reviews {
        rating
      }
    }
    filterRecipes(
      allergy: $allergy
      ingredients: $ingredients
      rating: $rating
      nutrition: $nutrition
      time: $time
    ) {
      id
      title
      description
      ingredients
      amountIngredients
      unitIngredients
      process
      timeCategory
      nutritionCategory
      portions
      authorId
      reviews {
        rating
      }
    }
    allergies {
      allergyTo
      userId
    }
    groups {
      id
      name
      usersId
      recipesId
      authorId
      groupRecipes {
        amountIngredients
        authorId
        description
        id
        ingredients
        nutritionCategory
        portions
        process
        reviews {
          authorId
          id
          rating
          recipeId
        }
        timeCategory
        title
        unitIngredients
      }
    }
  }
}
