query Group(
  $id: ID!
  $allergy: Float
  $ingredients: [Float!]
  $nutrition: Float
  $time: Float
) {
  group(id: $id) {
    id
    name
    usersId
    recipesId
    authorId
    groupRecipes {
      amountIngredients
      authorId
      description
      id
      ingredients
      nutritionCategory
      portions
      process
      reviews {
        authorId
        id
        rating
        recipeId
      }
      timeCategory
      title
      unitIngredients
    }
    filterGroupRecipes(
      allergy: $allergy
      ingredients: $ingredients
      nutrition: $nutrition
      time: $time
    ) {
      id
      title
      description
      ingredients
      amountIngredients
      unitIngredients
      process
      timeCategory
      nutritionCategory
      portions
      authorId
      reviews {
        rating
      }
    }
  }
}
